# Site settings
title: Chen Hui Jing
email: kakyou_tensai@yahoo.com
description: The chronicles of a self-taught designer and developer.
baseurl: ""
# url: "http://yourdomain.com" # the base hostname & protocol for your site
relative_permalinks: false
permalink: /blog/:title/
paginate: 7
paginate_path: "/blog/page:num"

twitter_username: hj_chen
github_username:  huijing
about: "I'm Hui Jing, a designer and front-end developer who builds Drupal-flavoured websites."

# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap
