# Site settings
title: Chen Hui Jing
email: kakyou_tensai@yahoo.com
description: The chronicles of a self-taught designer and developer.
baseurl: ""
url: "https://www.chenhuijing.com" 
enforce_ssl: www.chenhuijing.com   # without any protocol

relative_permalinks: false
permalink: /blog/:title/
paginate: 8
paginate_path: "/blog/page:num"

twitter_username: hj_chen
github_username:  huijing
drupalorg_username: huijing
about: "I'm Hui Jing, a designer and front-end developer who believes HTML and CSS are the foundation of the web."

# Build settings
highlighter: null

gems:
  - jekyll-sitemap
  - jekyll-paginate

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts

# Exclude files and folder
exclude:
  - node_modules
  - gulpfile.js
  - package.json
